import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Book Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          formButtonPrimary: "#558B78",
          footerActionLink: "text-como",
        },
      }}
    >
      <html className="bg-white" lang="en">
        <body suppressHydrationWarning={true} className={inter.className}>
          {children}
        </body>
        {/* <Toaster /> */}
      </html>
    </ClerkProvider>
  );
}
